name: seguridad_vial_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0

  # Firebase packages
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.1.0
  firebase_storage: ^12.3.3

  # Mapas y Geolocalización
  flutter_local_notifications: ^17.2.3
  flutter_tts: ^4.0.2

  # Sensores
  sensors_plus: ^6.0.1

  # Inteligencia Artificial
  tflite_flutter: ^0.11.0

  # Conexiones HTTP
  dio: ^5.0.0
  http: ^1.2.2

  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_fonts: ^6.2.1

  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  shared_preferences: ^2.1.0
  introduction_screen: ^3.1.4
  animated_text_kit: ^4.2.2
  lottie: ^3.1.2
  location: ^6.0.2
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/map_style.json
