// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnEA_xhFTULVAMoiy-meN5SrIRRHAablk',
    appId: '1:144792251921:web:d50d87b792e7e510660bb0',
    messagingSenderId: '144792251921',
    projectId: 'seguridad-vial-app',
    authDomain: 'seguridad-vial-app.firebaseapp.com',
    storageBucket: 'seguridad-vial-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxdcIr9tqlw_0p41OGPXXSGUBKJ5s_D_A',
    appId: '1:144792251921:android:b363160fdfbe6017660bb0',
    messagingSenderId: '144792251921',
    projectId: 'seguridad-vial-app',
    storageBucket: 'seguridad-vial-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpysGDGD6zI8F-oaNcPbWo6cxb3SSi9K4',
    appId: '1:144792251921:ios:d4cc454991b889ac660bb0',
    messagingSenderId: '144792251921',
    projectId: 'seguridad-vial-app',
    storageBucket: 'seguridad-vial-app.appspot.com',
    iosBundleId: 'com.example.seguridadVialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpysGDGD6zI8F-oaNcPbWo6cxb3SSi9K4',
    appId: '1:144792251921:ios:d4cc454991b889ac660bb0',
    messagingSenderId: '144792251921',
    projectId: 'seguridad-vial-app',
    storageBucket: 'seguridad-vial-app.appspot.com',
    iosBundleId: 'com.example.seguridadVialApp',
  );
}
